language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script: autoreconf -fvi && (./configure || cat configure) && make check
# script: echo $SHELL && $SHELL --version && autoconf --version && automake --version
