language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y autoconf-archive libgtest-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf-archive libgtest-dev; fi

os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script: autoreconf -fvi && ./configure && make check
# script: echo $SHELL && $SHELL --version && autoconf --version && automake --version
